export const FACTS = [
  { cat:'world', emoji:'🌊',
    text:'bestie did you know the Pacific Ocean is SO big it literally covers more than half the Earth\'s surface?? like the absolute AUDACITY of that body of water, it said \'I\'ll take the majority thanks\' fr fr no cap' },
  { cat:'world', emoji:'🐝',
    text:'bees are keeping us alive and NOT in a dramatic way — they pollinate 1/3 of all food we eat. protect the bees or we are NOT eating and that is NOT giving main character energy. bees understood the assignment bestie' },
  { cat:'world', emoji:'💧',
    text:'only 3% of Earth\'s water is fresh water and most of THAT is frozen in glaciers. we be fighting over 0.3% of accessible water. we literally live in a simulation and I am not okay about it' },
  { cat:'world', emoji:'🌋',
    text:'Mount Everest is tall but NOT the closest point to space — that\'s Mount Chimborazo in Ecuador bc Earth bulges at the equator. science ate and left ZERO crumbs periodt' },
  { cat:'world', emoji:'🦁',
    text:'female lions do 90% of the hunting but the males eat FIRST. the audacity. lions been running a patriarchy for millennia and I have so many thoughts about this fr' },
  { cat:'world', emoji:'🌿',
    text:'the Amazon rainforest produces 20% of Earth\'s oxygen and trees literally communicate through underground fungal networks — they are TEXTING each other. mother nature said \'group chat? invented it\'' },
  { cat:'world', emoji:'🧲',
    text:'Earth\'s magnetic north pole is MOVING toward Russia at 40 miles per year. the planet said \'location? it\'s complicated\' and honestly same, I respect the commitment to chaos' },
  { cat:'world', emoji:'🪸',
    text:'the Great Barrier Reef is so big it\'s visible from SPACE and it\'s the largest living structure on Earth. giving main character energy and we really need to protect it fr' },
  { cat:'world', emoji:'🐙',
    text:'octopuses have THREE hearts, BLUE blood, and can edit their own RNA on the fly. they are literally the most unhinged creatures and they\'ve been doing it way before humans thought science was cool' },
  { cat:'world', emoji:'🍯',
    text:'honey literally never expires — archaeologists found 3,000 year old honey in Egyptian tombs that was still edible. honey said \'expiration date? I don\'t know her\' and that\'s the most powerful food fact ever' },
  { cat:'history', emoji:'🏛️',
    text:'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramids. let that marinate bestie. we been miscalculating ancient history and I\'m choosing chaos about this' },
  { cat:'history', emoji:'👑',
    text:'Napoleon was actually AVERAGE HEIGHT for his era (5\'7") and the whole \'short king\' narrative was British war propaganda. we have been DECEIVED for 200 years and history class owes us an apology' },
  { cat:'history', emoji:'📚',
    text:'Oxford University is older than the Aztec Empire. they were already doing academic discourse while the Aztecs were still establishing their civilization. Oxford said \'vintage? we invented it\'' },
  { cat:'history', emoji:'🔬',
    text:'Marie Curie was so radioactive that her 1890s notebooks are kept in lead-lined boxes and need protective gear to read. queen was LITERALLY giving radioactive slay and we need to discuss how iconic this is' },
  { cat:'history', emoji:'🏃',
    text:'the first Olympic Games in 776 BC — athletes competed completely NAKED. ancient Greeks really said \'dress code? we don\'t know her\' and competed in the nude like it was nothing. unhinged behavior periodt' },
  { cat:'history', emoji:'🐱',
    text:'ancient Egyptians shaved their eyebrows when their cat died as a sign of mourning. cats have been main characters since literally forever and ancient Egypt understood the assignment way before us' },
  { cat:'history', emoji:'⚔️',
    text:'the Hundred Years\' War between England and France lasted 116 YEARS. they couldn\'t even do basic math during their own beef. the historical drama of it all is sending me to the afterlife fr' },
  { cat:'history', emoji:'🎶',
    text:'Beethoven composed some of his greatest works while almost completely deaf. he literally could not hear his own music and still gave us absolute bangers. the main character energy is unprecedented' },
  { cat:'history', emoji:'🔥',
    text:'the Library of Alexandria burned multiple times and we lost CENTURIES of knowledge. we could\'ve been so advanced bestie. this is still making me genuinely unwell and it happened 2000 years ago' },
  { cat:'geography', emoji:'🦘',
    text:'Australia has more venomous animals than ANYWHERE else on Earth and Australians just... vibe with it daily?? they wake up next to spiders that could delete you. unhinged main character behavior' },
  { cat:'geography', emoji:'🇷🇺',
    text:'Russia spans 11 TIME ZONES. E-L-E-V-E-N. while you\'re having breakfast in Moscow, someone in Vladivostok is going to sleep. Russia said \'timezone? yes, all of them\' and geography had no choice' },
  { cat:'geography', emoji:'🏜️',
    text:'the Sahara Desert was a RAINFOREST with lakes and rivers just 5,000 years ago. ancient humans were literally chilling by water where there\'s now scorching sand. Earth did a complete villain arc' },
  { cat:'geography', emoji:'🏔️',
    text:'Canada has more lakes than ALL other countries combined. Canada quietly hoarded the world\'s freshwater and nobody talks about this enough. sneaky queen behavior and I respect the long game' },
  { cat:'geography', emoji:'🌊',
    text:'the Dead Sea is so salty you literally CANNOT sink in it — you just float there like a human pool noodle. nature said \'flotation device? I got you bestie\' and built the Dead Sea. physics said slay' },
  { cat:'geography', emoji:'🧊',
    text:'Antarctica is technically the world\'s largest DESERT because deserts are defined by low precipitation, not temperature. the cold = not a desert thing was a lie we all believed and I\'m choosing chaos' },
  { cat:'geography', emoji:'🌺',
    text:'Hawaii is moving toward Japan at 2.5 inches per year due to tectonic drift. in 50 million years Hawaii might fuse with Asia. geological drift said \'distance? temporary bestie\'' },
  { cat:'geography', emoji:'🗾',
    text:'Japan has vending machines selling hot food, fresh flowers, umbrellas, crabs, and even CARS. Japan is literally living in 3026 while we\'re still arguing about what goes in vending machines' },
  { cat:'geography', emoji:'🌍',
    text:'Africa is SO big that you could fit the US, China, India, and most of Europe INSIDE it and still have room. our maps have been lying about continent sizes and that\'s the most map-pilled revelation' },
  { cat:'geography', emoji:'🇳🇴',
    text:'Norway has a town where it\'s literally illegal to die — if you\'re terminally ill you\'re flown out. the permafrost can\'t decompose bodies so they just said \'no dying allowed here\' and I respect the chaos' },
  { cat:'civics', emoji:'📜',
    text:'the US Constitution is the OLDEST written national constitution still in use, serving timeless looks since 1787. the founding era understood that good documents slap forever and that\'s genuinely impressive' },
  { cat:'civics', emoji:'🇮🇸',
    text:'Iceland has the world\'s oldest parliament — the Althing, founded in 930 AD. they been doing democracy since before it was cool and that\'s the most lowkey main character move from a tiny island nation' },
  { cat:'civics', emoji:'🗳️',
    text:'in Belgium, voting is literally MANDATORY. you HAVE to vote or you get fined. Americans be like \'ugh voting is inconvenient\' while Belgians are legally obligated and nobody talks about this energy difference' },
  { cat:'civics', emoji:'🇳🇿',
    text:'New Zealand was the FIRST country to give women the right to vote in 1893 — 27 years before the US. they were running a full feminist arc while everyone else was still debating it' },
  { cat:'civics', emoji:'🏛️',
    text:'the UN has 193 member countries out of 195 recognized nations. Vatican City really said \'international organizations? we don\'t do that here\' and that\'s honestly a power move' },
  { cat:'civics', emoji:'⚖️',
    text:'the US Supreme Court has 9 justices because CONGRESS sets that number — it is NOT in the Constitution. that number could theoretically be changed by law and this information is doing damage to my brain' },
  { cat:'civics', emoji:'🇮🇳',
    text:'India is the world\'s largest democracy with 1.4 BILLION people and 900+ million eligible voters. India said \'democracy? we\'re gonna go big\' and that scale is genuinely mind-blowing' },
  { cat:'civics', emoji:'🌐',
    text:'the EU has its own parliament, court, and currency used by 20 countries — it\'s basically a country that refuses to be called a country. the most complicated political situationship in modern history' },
  { cat:'civics', emoji:'🇨🇭',
    text:'Switzerland has held over 600 referendums since 1848 — citizens vote directly on laws constantly. they basically crowdsource their entire government and that\'s the most democratic behavior ever witnessed fr' },
  { cat:'civics', emoji:'🌱',
    text:'Ecuador and Bolivia have granted legal RIGHTS to nature itself in their constitutions. rivers and forests can be protected in court like a person. the planet said \'legal rights?\' and two countries said \'slay\'' },
];

export const QUIZ = [
  { q:'bestie which is the largest ocean on Earth? 🌊',
    opts:['Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean'], ans:1,
    exp:'the Pacific covers MORE than half the Earth\'s surface — it ate everyone\'s portion and felt zero remorse 💅' },
  { q:'which country secretly hoards more lakes than any other? 🏔️',
    opts:['Russia','United States','Canada','Brazil'], ans:2,
    exp:'Canada has more lakes than ALL other countries combined. quietly collecting freshwater since forever — we respect the long game' },
  { q:'which ancient civilization literally worshipped cats?? 🐱',
    opts:['Ancient Greeks','Ancient Egyptians','Ancient Romans','Mesopotamians'], ans:1,
    exp:'Egyptians were the OG cat girlies — they shaved their eyebrows when their cat died. legend behavior periodt' },
  { q:'which country gave women the right to vote FIRST? 🗳️',
    opts:['United States','United Kingdom','New Zealand','France'], ans:2,
    exp:'New Zealand said \'women\'s rights\' in 1893 — 27 years before the US. serving feminist queen behavior since the 1800s' },
  { q:'the Sahara Desert used to be a... 🌿',
    opts:['frozen tundra','lush rainforest','shallow ocean','volcanic wasteland'], ans:1,
    exp:'5,000 years ago it was green and full of lakes. Earth did a full villain arc and we didn\'t get a say in it' },
  { q:'how many time zones does Russia span? 🕐',
    opts:['6 time zones','8 time zones','11 time zones','15 time zones'], ans:2,
    exp:'ELEVEN. Russia said \'we\'ll take all of them thanks\' and geography had no choice but to comply' },
  { q:'Cleopatra\'s life was closer in time to which event? 📅',
    opts:['The Moon landing (1969)','Building the pyramids (~2500 BC)','They\'re equally distant','Fall of Rome (476 AD)'], ans:0,
    exp:'Cleopatra (69 BC) is closer to the Moon landing than to the pyramids. ancient history is NOT what we thought bestie' },
  { q:'which country makes voting LEGALLY mandatory? 🗳️',
    opts:['Netherlands','Sweden','Belgium','Denmark'], ans:2,
    exp:'Belgium said civic duty is non-negotiable and honestly that\'s a whole political philosophy right there' },
  { q:'Antarctica is technically classified as a... 🧊',
    opts:['polar ice cap','tundra biome','desert','permafrost zone'], ans:2,
    exp:'technically a desert because of low precipitation. the cold = not desert assumption was a lie we all lived with' },
  { q:'what was Napoleon\'s actual height? 👑',
    opts:['5\'2" (very short)','5\'5" (below avg)','5\'7" (average)','5\'10" (tall)'], ans:2,
    exp:'5\'7" — average for his time. the short king thing was British propaganda and we believed it for 200 years. we been gaslit' },
  { q:'which institution is OLDER than the Aztec Empire? 📚',
    opts:['Harvard University','Oxford University','Cambridge University','Yale University'], ans:1,
    exp:'Oxford was already doing academics while the Aztec Empire was being established. vintage doesn\'t even cover it' },
  { q:'how many hearts does an octopus have? 🐙',
    opts:['1 heart','2 hearts','3 hearts','4 hearts'], ans:2,
    exp:'THREE hearts and blue blood. octopuses are completely unhinged creatures and they\'ve always known it' },
];

export const NEWS_VIBES = [
  'this is giving breaking news energy fr 📰',
  'bestie this affects all of us no cap 🌍',
  'the world really said \'we\'re not done yet\' huh 💅',
  'this story is giving main character moment 🎬',
  'lowkey important tea you need to know about 🍵',
  'the audacity of this news story periodt 😤',
  'this is so real and we should be talking about it 👀',
  'staying educated era activated ✨',
  'stay educated bestie this genuinely matters 🧠',
  'girlies and boys this is important tea 🫖',
  'not me learning about the world through a vibe check 🌐',
];

export const TICKER_ITEMS = [
  '✨ 96% of the ocean is still UNEXPLORED bestie 🌊',
  '💅 honey never expires — 3,000yr old honey from Egypt still edible fr',
  '🌟 a day on Venus is longer than a year on Venus — chaotic planet behavior',
  '🔥 the Eiffel Tower grows 6 inches taller every summer due to heat periodt',
  '💀 Cleopatra lived closer to the iPhone era than to the pyramids no cap',
  '🌿 trees literally TEXT each other through underground fungal networks',
  '✨ Oxford University is older than the Aztec Empire and that\'s sending me',
  '🐙 octopuses have 3 hearts and blue blood — completely unhinged creatures',
  '💫 more possible chess games exist than atoms in the observable universe bestie',
  '🦁 female lions do 90% of hunting but males eat first — patriarchy started with lions fr',
  '🧊 Antarctica is technically a desert because science said so bestie',
  '🌺 Hawaii is drifting toward Japan at 2.5 inches per year — geology is slow but steady',
  '📜 the US Bill of Rights took 2 years to ratify after the Constitution was written',
  '🇮🇸 Iceland\'s parliament was founded in 930 AD — oldest in the world fr',
  '🍯 a bee visits up to 5,000 flowers to make ONE tablespoon of honey — she is WORKING',
  '🌊 the Pacific Ocean is wider than the Moon\'s diameter — big ocean energy',
  '🐋 blue whale hearts are the size of a small car and audible from 2 miles away',
  '⚡ lightning strikes Earth about 100 times per second and that\'s so unhinged',
];

export const HEADER_EMOJIS = ['✨','💫','🌟','💅','🔥','💖','🌸','🦋','⭐','🌈','💜','🩷','🪄','🌙'];

export const ACHIEVEMENTS = [
  { trigger:1,  msg:'first quiz answered! big brain era begins 🧠' },
  { trigger:3,  msg:'3 in a row! you\'re literally so educated bestie ✨' },
  { trigger:5,  msg:'5 streak!! you understood the assignment 💅' },
  { trigger:10, msg:'10 STREAK!! you are literally a genius no cap 🌟' },
];

export const SPARK_POOLS = {
  pink:   ['🌸','💖','🩷','💗','🌺','🎀','💝','🫧','✨','💓','🦋','🌷'],
  blue:   ['💙','❄️','💎','🌊','💠','🫧','🔷','⭐','🌀','🫐','🧊','💫'],
  black:  ['⭐','✨','💫','🌟','👑','🔥','⚡','🪄','💛','🌙','🗝️','💎'],
  yellow: ['🌻','💛','☀️','🌟','🍋','🌼','✨','💫','🎇','⭐','🌞','🍯'],
};
